/**
 * Conversation drag payloads cross a DOM dataTransfer boundary and must not
 * be assumed to have the structure generated by the app's own drag handler.
 * Reject malformed or mixed-type payloads before staging any .eml files.
 */
export function threadIdsFromDragPayload(payload: string): string[] {
  if (typeof payload !== 'string' || !payload) {
    return [];
  }

  try {
    const parsed = JSON.parse(payload);
    if (!parsed || !Array.isArray(parsed.threadIds)) {
      return [];
    }

    if (
      !parsed.threadIds.every(
        (id: unknown) => typeof id === 'string' && id.length > 0 && id.trim() === id
      )
    ) {
      return [];
    }

    // Duplicate identifiers can otherwise create multiple identical attachments.
    return Array.from(new Set<string>(parsed.threadIds));
  } catch {
    return [];
  }
}
